query ActivityEvents(
  $where: activityEventFilter
  $orderBy: String
  $orderDirection: String
  $limit: Int
  $offset: Int
) {
  activityEvents(
    where: $where
    orderBy: $orderBy
    orderDirection: $orderDirection
    limit: $limit
    offset: $offset
  ) {
    totalCount
    items {
      id
      chainId
      timestamp
      payEvent {
        id
        amount
        beneficiary
        memo
        timestamp
        feeFromProject
        newlyIssuedTokenCount
        from
        txHash
        amountUsd
        caller
        distributionFromProjectId
        projectId
        project {
          id
          projectId
          handle
        }
      }
      cashOutTokensEvent {
        id
        timestamp
        txHash
        from
        beneficiary
        reclaimAmount
        cashOutCount
        metadata
        project {
          id
          projectId
          handle
        }
      }
    }
  }
}
